name: Docker Flow

on: 
  push:
    branches:
      - ku
  watch:
    branches:
      - ku
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Retrieve version
      run: |
        echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 10) >> $GITHUB_ENV
    - name: Build the versioned and the latest Docker image
      run: docker build . -t gentlemanhu/theia:${{ env.VERSION }} -t gentlemanhu/theia:latest
    - name: Push the versioned Docker image
      run: docker push gentlemanhu/theia:${{ env.VERSION }}
    - name: Push the latest Docker image
      run: docker push gentlemanhu/theia:latest  